export const publicBusinessExamples = [
  { title: 'Mercados y despensas', description: 'Organizá productos, precios, existencias y ventas de mostrador.', tools: 'Ventas · Inventario · Caja', href: '/saas/soluciones#ventas' },
  { title: 'Tiendas de ropa', description: 'Administrá prendas con variantes de talle y color, y publicá tu catálogo.', tools: 'Variantes · Inventario · Tienda online', href: '/saas/soluciones#inventario' },
  { title: 'Barberías y peluquerías', description: 'Prepará tus servicios y horarios por profesional para gestionar turnos.', tools: 'Servicios · Agenda · Clientes', href: '/saas/soluciones#reservas' },
  { title: 'Negocios con reservas', description: 'Ofrecé servicios con duración y horarios disponibles; habilitá reservas online cuando estés listo.', tools: 'Servicios · Turnos · Reservas online', href: '/saas/soluciones#reservas' },
  { title: 'Tecnología, ferreterías y comercios', description: 'Buscá productos por código, consultá stock y registrá tus operaciones.', tools: 'Catálogo · Códigos de barras · Ventas', href: '/saas/soluciones#inventario' },
  { title: 'Talleres y servicios técnicos', description: 'Registrá equipos, diagnósticos, repuestos y el avance de cada reparación.', tools: 'Reparaciones · Repuestos · Seguimiento', href: '/saas/soluciones#reparaciones' },
]

export const publicSolutions = [
  { id: 'ventas', title: 'Ventas y caja', problem: 'Necesitás registrar lo que vendés y revisar los cobros del día.', description: 'Buscá productos, registrá ventas y consultá los movimientos de caja.', example: 'Un mercado registra la compra del cliente y revisa su turno de caja.', requirement: 'Requiere los módulos POS e inventario; las acciones de caja dependen de los permisos.', steps: ['Prepará productos y precios.', 'Registrá la venta y el medio de pago.', 'Revisá movimientos y cierre de caja.'] },
  { id: 'inventario', title: 'Productos e inventario', problem: 'Querés encontrar cada producto y saber qué existencias tiene.', description: 'Organizá categorías, códigos, variantes y stock desde un catálogo compartido.', example: 'Una tienda de ropa distingue la misma prenda por talle y color.', requirement: 'La capacidad de productos y sucursales depende del plan. El control avanzado requiere inventario avanzado.', steps: ['Cargá productos y sus variantes.', 'Registrá existencias y movimientos.', 'Consultá stock antes de vender.'] },
  { id: 'reservas', title: 'Servicios, agenda y reservas', problem: 'Necesitás organizar las citas sin depender de una lista de mensajes.', description: 'Configurá servicios, duración, profesionales y horarios; habilitá la reserva online para los servicios que elijas.', example: 'Una barbería ofrece un corte de 30 minutos con los profesionales disponibles.', requirement: 'Requiere el módulo Servicios, una agenda configurada y reservas online habilitadas para publicarlas.', steps: ['Definí servicios y duración.', 'Configurá profesionales y horarios.', 'Gestioná turnos o recibí reservas online.'] },
  { id: 'reparaciones', title: 'Reparaciones y seguimiento', problem: 'Querés saber en qué estado está cada equipo y qué trabajos se realizaron.', description: 'Registrá la recepción, el diagnóstico, los repuestos y el estado de la reparación; ofrecé la consulta pública del seguimiento.', example: 'Un taller registra un celular y actualiza su estado hasta la entrega.', requirement: 'Requiere Reparaciones. La cantidad de órdenes y fotos depende del plan; el cliente debe validar su acceso al seguimiento.', steps: ['Registrá el equipo y la falla.', 'Actualizá estado, costos y repuestos.', 'Coordiná el cobro y la entrega.'] },
  { id: 'clientes', title: 'Clientes e historial', problem: 'Necesitás tener los datos del cliente a mano para atenderlo mejor.', description: 'Mantené sus datos y consultá la información disponible de sus operaciones desde el negocio.', example: 'Una peluquería encuentra los datos de contacto de un cliente al gestionar su turno.', requirement: 'Requiere Clientes. Créditos, promociones y otras herramientas tienen sus propios módulos y permisos.', steps: ['Buscá al cliente antes de crear otra ficha.', 'Completá sus datos de contacto.', 'Consultá sus operaciones según tus permisos.'] },
  { id: 'tienda-online', title: 'Tienda online y pedidos', problem: 'Querés mostrar tu negocio y tus productos fuera del mostrador.', description: 'Personalizá tu sitio y publicá el catálogo que elijas. Gestioná pedidos y entregas cuando esos módulos estén disponibles.', example: 'Una tienda de ropa comparte su catálogo público con sus clientes.', requirement: 'Requiere Ecommerce para la tienda; Pedidos y Delivery para esos flujos. La publicación debe configurarse en el negocio.', steps: ['Prepará la información del negocio.', 'Elegí qué productos publicar.', 'Configurá cómo recibir consultas o pedidos.'] },
]
