import {
  Boxes,
  Building2,
  ClipboardList,
  CreditCard,
  Crown,
  Download,
  Globe,
  Handshake,
  MousePointerClick,
  ShieldCheck,
  ShoppingCart,
  TicketPercent,
  TrendingUp,
  Truck,
  Users,
  Warehouse,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

/** Ícono de cada feature del catálogo (plan-feature-catalog.ts). */
export const PLAN_FEATURE_ICONS: Record<string, LucideIcon> = {
  pos: ShoppingCart,
  ecommerce: Globe,
  orders: ClipboardList,
  delivery: Truck,
  promotions: TicketPercent,
  credits: CreditCard,
  inventory: Boxes,
  inventoryAdmin: Warehouse,
  repairs: Wrench,
  services: Handshake,
  crm: Users,
  analytics: TrendingUp,
  webAnalytics: MousePointerClick,
  security: ShieldCheck,
  reports: Download,
  users: Users,
  branches: Building2,
  support: Crown,
}
