-- Generated by CLI as 20261008225127, ordered after existing agenda dependencies.
-- DRAFT, NOT READY TO APPLY. Kept outside migrations until atomic writes are verified.
-- Stage 1 foundation only; public activation requires subsequent atomic-write migration.
begin;

alter table public.agenda_settings
  add column professional_selection text not null default 'optional'
    check (professional_selection in ('disabled', 'optional', 'required')),
  add column booking_revision bigint not null default 1 check (booking_revision > 0);
alter table public.agenda_professionals
  add column online_visible boolean not null default true,
  add column opening_hours jsonb check (opening_hours is null or jsonb_typeof(opening_hours) = 'object'),
  add constraint agenda_professionals_tenant_identity unique (organization_id, id);
alter table public.products add constraint products_agenda_tenant_identity unique (organization_id, id);
alter table public.appointments add constraint appointments_agenda_tenant_identity unique (organization_id, id);
alter table public.agenda_services add column buffer_minutes integer not null default 0
  check (buffer_minutes between 0 and 120);
alter table public.appointments
  add column buffer_minutes integer not null default 0 check (buffer_minutes between 0 and 120),
  add column occupied_until timestamptz;
update public.appointments set occupied_until = ends_at;
alter table public.appointments alter column occupied_until set not null;
alter table public.appointments add constraint appointments_occupied_interval
  check (occupied_until = ends_at + make_interval(mins => buffer_minutes));

create function public.set_appointment_occupied_until() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.occupied_until := new.ends_at + make_interval(mins => new.buffer_minutes);
  return new;
end $$;
revoke all on function public.set_appointment_occupied_until() from public, anon, authenticated;
create trigger appointments_00_occupied_until before insert or update on public.appointments
  for each row execute function public.set_appointment_occupied_until();

create table public.agenda_professional_service_rates (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  professional_id uuid not null,
  product_id uuid not null,
  price numeric(14,2) check (price >= 0),
  duration_minutes integer check (duration_minutes between 5 and 600),
  buffer_minutes integer check (buffer_minutes between 0 and 120),
  primary key (organization_id, professional_id, product_id),
  foreign key (organization_id, professional_id) references public.agenda_professionals(organization_id, id) on delete cascade,
  foreign key (organization_id, product_id) references public.products(organization_id, id) on delete cascade
);

create table public.agenda_time_off (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  professional_id uuid,
  starts_at timestamptz not null,
  ends_at timestamptz not null check (ends_at > starts_at),
  reason text check (char_length(reason) <= 300),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  foreign key (organization_id, professional_id) references public.agenda_professionals(organization_id, id) on delete cascade
);
create index agenda_time_off_interval on public.agenda_time_off(organization_id, starts_at, ends_at);

create table public.agenda_booking_quotes (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  professional_id uuid,
  product_id uuid not null,
  service_name text not null check (char_length(service_name) between 1 and 200),
  price numeric(14,2) not null check (price >= 0),
  hide_price boolean not null,
  duration_minutes integer not null check (duration_minutes between 5 and 600),
  buffer_minutes integer not null check (buffer_minutes between 0 and 120),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  occupied_until timestamptz not null,
  revision bigint not null check (revision > 0),
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  created_at timestamptz not null default now(),
  idempotency_key uuid,
  request_hash text,
  appointment_id uuid,
  unique (organization_id, idempotency_key),
  foreign key (organization_id, professional_id) references public.agenda_professionals(organization_id, id),
  foreign key (organization_id, product_id) references public.products(organization_id, id),
  foreign key (organization_id, appointment_id) references public.appointments(organization_id, id),
  check (ends_at = starts_at + make_interval(mins => duration_minutes)),
  check (occupied_until = ends_at + make_interval(mins => buffer_minutes)),
  check (expires_at > created_at)
);
create index agenda_booking_quotes_expiry on public.agenda_booking_quotes(expires_at);

alter table public.agenda_professional_service_rates enable row level security;
alter table public.agenda_time_off enable row level security;
alter table public.agenda_booking_quotes enable row level security;
revoke all on public.agenda_professional_service_rates, public.agenda_time_off, public.agenda_booking_quotes from anon, authenticated;
grant select, insert, update, delete on public.agenda_professional_service_rates to authenticated;
-- Time off is server-written only, through the future conflict-checking RPC.
grant select on public.agenda_time_off to authenticated;
grant all on public.agenda_professional_service_rates, public.agenda_time_off, public.agenda_booking_quotes to service_role;
create policy agenda_rates_read on public.agenda_professional_service_rates for select to authenticated
  using (public.get_org_role(organization_id) is not null);
create policy agenda_rates_write on public.agenda_professional_service_rates for all to authenticated
  using (public.has_org_permission(organization_id, 'settings.manage'))
  with check (public.has_org_permission(organization_id, 'settings.manage'));
create policy agenda_time_off_read on public.agenda_time_off for select to authenticated
  using (public.get_org_role(organization_id) is not null);
-- No public/authenticated policy for quotes: prices and customer retry data are private.
commit;
