'use client'

import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import type { AdminFinanceFilters } from '@/hooks/use-admin-finances'
import { ExpenseDialog, type FinanceCategory } from './ExpenseDialog'
import { PaymentDialog } from './PaymentDialog'

type Obligation = { id: string; concept: string | null; amount: number; paid_amount: number; due_date: string | null; status: string; finance_categories?: { name?: string } | null }
const money = (value: number) => `₲ ${Math.round(value).toLocaleString('es-PY')}`

export function ExpensesPanel({ organizationId, branchId, filters, onChanged }: { organizationId: string; branchId: string | null | undefined; filters: AdminFinanceFilters; onChanged: () => unknown | Promise<unknown> }) {
  const [categories, setCategories] = useState<FinanceCategory[]>([])
  const [obligations, setObligations] = useState<Obligation[]>([])
  const [error, setError] = useState<string | null>(null)
  const [expenseOpen, setExpenseOpen] = useState(false)
  const [paying, setPaying] = useState<Obligation | null>(null)
  const [voiding, setVoiding] = useState<Obligation | null>(null)
  const [isVoiding, setIsVoiding] = useState(false)
  async function load() { const params = new URLSearchParams({ organizationId, startDate: filters.startDate, endDate: filters.endDate, pageSize: '50' }); if (branchId) params.set('branchId', branchId); const [categoryResponse, obligationResponse] = await Promise.all([fetch(`/api/admin/finances/categories?organizationId=${organizationId}`), fetch(`/api/admin/finances/obligations?${params.toString()}`)]); const categoriesPayload = await categoryResponse.json().catch(() => null) as { categories?: FinanceCategory[]; error?: string } | null; const obligationsPayload = await obligationResponse.json().catch(() => null) as { obligations?: Obligation[]; error?: string } | null; if (!categoryResponse.ok || !obligationResponse.ok) { setError(categoriesPayload?.error ?? obligationsPayload?.error ?? 'No se pudieron cargar los gastos.'); return } setError(null); setCategories(categoriesPayload?.categories ?? []); setObligations(obligationsPayload?.obligations ?? []) }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [organizationId, branchId, filters.startDate, filters.endDate])
  async function changed() { await load(); await onChanged() }
  async function voidExpense() { if (!voiding || !branchId || isVoiding) return; setIsVoiding(true); const response = await fetch(`/api/admin/finances/obligations/${voiding.id}?organizationId=${organizationId}`, { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ branchId, reason: 'Anulado desde Finanzas' }) }); const payload = await response.json().catch(() => null) as { error?: string } | null; setIsVoiding(false); if (!response.ok) { setError(payload?.error ?? 'No se pudo anular el gasto.'); return } setVoiding(null); await changed() }
  return <section className="space-y-4 rounded-lg border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Gastos y obligaciones</h2><p className="text-sm text-muted-foreground">Registra obligaciones, recurrencias y pagos parciales sin alterar los totales locales.</p></div><Button onClick={() => setExpenseOpen(true)} disabled={!branchId}>Nuevo gasto</Button></div>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}<div className="overflow-x-auto"><table className="w-full min-w-[42rem] text-sm"><thead><tr className="border-b text-left"><th className="p-2">Concepto</th><th className="p-2">Estado</th><th className="p-2">Importe</th><th className="p-2">Pendiente</th><th className="p-2"><span className="sr-only">Acciones</span></th></tr></thead><tbody>{obligations.map((item) => <tr key={item.id} className="border-b"><td className="p-2"><p>{item.concept ?? item.finance_categories?.name ?? 'Gasto'}</p><p className="text-xs text-muted-foreground">Vence: {item.due_date ?? 'Sin vencimiento'}</p></td><td className="p-2">{item.status}</td><td className="p-2">{money(Number(item.amount))}</td><td className="p-2">{money(Math.max(0, Number(item.amount) - Number(item.paid_amount)))}</td><td className="p-2 text-right"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => setPaying(item)} disabled={['paid', 'voided'].includes(item.status)}>Pagar</Button><Button size="sm" variant="ghost" onClick={() => setVoiding(item)} disabled={['paid', 'voided'].includes(item.status)}>Anular</Button></div></td></tr>)}</tbody></table></div><ExpenseDialog open={expenseOpen} onOpenChange={setExpenseOpen} organizationId={organizationId} branchId={branchId} categories={categories} onSaved={changed} /><PaymentDialog open={Boolean(paying)} onOpenChange={(open) => !open && setPaying(null)} organizationId={organizationId} obligationId={paying?.id} branchId={branchId} onSaved={changed} /><AlertDialog open={Boolean(voiding)} onOpenChange={(open) => !open && setVoiding(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Anular este gasto?</AlertDialogTitle><AlertDialogDescription>La anulación queda auditada y no se puede deshacer desde esta pantalla.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={voidExpense} disabled={isVoiding}>{isVoiding ? 'Anulando…' : 'Confirmar anulación'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
}
